language: bash
dist: xenial
group: travis_latest
sudo: required

if: |
  branch = master AND \
  ! commit_message =~ /readme.md/ AND \
  ! commit_message =~ /docker-compose.yml/ OR \
  type = cron

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - ARCHITECTURES="arm arm64 amd64"
    - BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    - BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}"
    - DOCKER_DESCRIPTION="ubuntu base image"
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="ubuntu"
    - DOCKER_TAG="rolling"
    - DOCKER_URL="https://www.ubuntu.com/"
    - SCHEMA_VERSION="1.0"
    - UBUNTU_CODENAME="$(curl -sL https://raw.githubusercontent.com/tianon/docker-brew-ubuntu-core/master/rolling)"
    - VCS_REF="$(git rev-parse --short HEAD)"
    - VCS_URL="$(git remote get-url origin | head -c-5)"

before_install:
  - sudo /sbin/sysctl -w net.ipv4.conf.all.forwarding=1
  - docker version

install:
  - sudo docker run --privileged linuxkit/binfmt:v0.6
  - sudo docker run --privileged -d -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/arm --oci-worker-platform linux/armhf --oci-worker-platform linux/arm64 --oci-worker-platform linux/amd64
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
  - export BUILDKIT_HOST=tcp://0.0.0.0:1234

before_script:
  - sed -i -e '/^$/d' -e 's/^[ \t]*//' -e '/^#/d' Dockerfile*

script:
  - sudo bash ./travis/build.sh
  - sudo bash ./travis/deploy.sh

after_success:
  # Trigger java_docker build
  - >
    curl -X POST
    -H "Content-Type: application/json"
    -H "Travis-API-Version: 3"
    -H "Accept: application/json"
    -H "Authorization: token ${TRAVIS_API_TOKEN}"
    -d '{"request": {"message": "Push from stlouisn/ubuntu", "branch": "master"}}'
    'https://api.travis-ci.org/repo/stlouisn%2Fjava_docker/requests'
  # Trigger python_docker build
  - >
    curl -X POST
    -H "Content-Type: application/json"
    -H "Travis-API-Version: 3"
    -H "Accept: application/json"
    -H "Authorization: token ${TRAVIS_API_TOKEN}"
    -d '{"request": {"message": "Push from stlouisn/ubuntu", "branch": "master"}}'
    'https://api.travis-ci.org/repo/stlouisn%2Fpython_docker/requests'
  # Trigger mono_docker build
  - >
    curl -X POST
    -H "Content-Type: application/json"
    -H "Travis-API-Version: 3"
    -H "Accept: application/json"
    -H "Authorization: token ${TRAVIS_API_TOKEN}"
    -d '{"request": {"message": "Push from stlouisn/ubuntu", "branch": "master"}}'
    'https://api.travis-ci.org/repo/stlouisn%2Fmono_docker/requests'
  # Trigger traefik_docker build
  - >
    curl -X POST
    -H "Content-Type: application/json"
    -H "Travis-API-Version: 3"
    -H "Accept: application/json"
    -H "Authorization: token ${TRAVIS_API_TOKEN}"
    -d '{"request": {"message": "Push from stlouisn/ubuntu", "branch": "master"}}'
    'https://api.travis-ci.org/repo/stlouisn%2Ftraefik_docker/requests'
  # Trigger openvpn_docker build
  - >
    curl -X POST
    -H "Content-Type: application/json"
    -H "Travis-API-Version: 3"
    -H "Accept: application/json"
    -H "Authorization: token ${TRAVIS_API_TOKEN}"
    -d '{"request": {"message": "Push from stlouisn/ubuntu", "branch": "master"}}'
    'https://api.travis-ci.org/repo/stlouisn%2Fopenvpn_docker/requests'

notifications:
  email:
    on_success: never
    on_failure: change
