language: bash
dist: trusty
group: travis_latest
sudo: required

if: |
  branch = master AND \
  NOT commit_message =~ /readme.md/ AND \
  NOT commit_message =~ /docker-compose.yml/

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - BUILD_DATE="`date -u +%Y-%m-%dT%H:%M:%SZ`"
    - BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
    - DOCKER_DESCRIPTION="ubuntu base image"
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="ubuntu"
    - DOCKER_URL="https://www.ubuntu.com/"
    - SCHEMA_VERSION="1.0"	
    - VCS_REF="`git rev-parse --short HEAD`"	
    - VCS_URL="`git remote get-url origin | head -c-5`"
  matrix:
    - DOCKER_TAG="rolling"
      DOCKER_VERSION="`curl -s https://raw.githubusercontent.com/tianon/docker-brew-ubuntu-core/master/rolling`"

before_install:
  - docker version
  - sudo /sbin/sysctl -w net.ipv4.conf.all.forwarding=1

install:

before_script:
  - sed -i -e '/^$/d' -e 's/^[ \t]*//' -e '/^#/d' Dockerfile

script:
  - docker build --tag ${DOCKER_USERNAME}/${DOCKER_NAME}:temp --pull .
  - docker create --name ubuntu ${DOCKER_USERNAME}/${DOCKER_NAME}:temp /bin/bash -c exit
  - docker export -o ubuntu-image.tar `docker ps -a | grep ubuntu  | awk -F ' ' {'print $1'}`
  - docker import ubuntu-image.tar --message "stlouisn/ubuntu:rolling"

after_success:
  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}

  # Trigger java_docker build
  - >
    curl -X POST
    -H "Content-Type: application/json"
    -H "Travis-API-Version: 3"
    -H "Accept: application/json"
    -H "Authorization: token ${TRAVIS_API_TOKEN}"
    -d '{"request": {"message": "Push from stlouisn/ubuntu", "branch": "master"}}'
    'https://api.travis-ci.org/repo/stlouisn%2Fjava_docker/requests'

  # Trigger python_docker build
  - >
    curl -X POST
    -H "Content-Type: application/json"
    -H "Travis-API-Version: 3"
    -H "Accept: application/json"
    -H "Authorization: token ${TRAVIS_API_TOKEN}"
    -d '{"request": {"message": "Push from stlouisn/ubuntu", "branch": "master"}}'
    'https://api.travis-ci.org/repo/stlouisn%2Fpython_docker/requests'

  # Trigger mono_docker build
  - >
    curl -X POST
    -H "Content-Type: application/json"
    -H "Travis-API-Version: 3"
    -H "Accept: application/json"
    -H "Authorization: token ${TRAVIS_API_TOKEN}"
    -d '{"request": {"message": "Push from stlouisn/ubuntu", "branch": "master"}}'
    'https://api.travis-ci.org/repo/stlouisn%2Fmono_docker/requests'

  # Trigger traefik_docker build
  - >
    curl -X POST
    -H "Content-Type: application/json"
    -H "Travis-API-Version: 3"
    -H "Accept: application/json"
    -H "Authorization: token ${TRAVIS_API_TOKEN}"
    -d '{"request": {"message": "Push from stlouisn/ubuntu", "branch": "master"}}'
    'https://api.travis-ci.org/repo/stlouisn%2Ftraefik_docker/requests'

  # Trigger pi-hole_docker build

  # Trigger openvpn_docker build
  - >
    curl -X POST
    -H "Content-Type: application/json"
    -H "Travis-API-Version: 3"
    -H "Accept: application/json"
    -H "Authorization: token ${TRAVIS_API_TOKEN}"
    -d '{"request": {"message": "Push from stlouisn/ubuntu", "branch": "master"}}'
    'https://api.travis-ci.org/repo/stlouisn%2Fopenvpn_docker/requests'

#      # Trigger nextcloud_docker build
#      - >
#        curl -X POST
#        -H "Content-Type: application/json"
#        -H "Travis-API-Version: 3"
#        -H "Accept: application/json"
#        -H "Authorization: token ${TRAVIS_API_TOKEN}"
#        -d '{"request": {"message": "Push from stlouisn/ubuntu", "branch": "master"}}'
#        'https://api.travis-ci.org/repo/stlouisn%2Fnextcloud_docker/requests'

notifications:
  email:
    on_success: never
    on_failure: change
